spring.application.name=FinSecureProject
server.port=8085

spring.datasource.username=root
spring.datasource.password=Mayank@123

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/finsecure3
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mayanksharma00819@gmail.com
spring.mail.password=mgsgvtalvofpirhi

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.mail.from=mayanksharma00819@gmail.com

app.MAX_HOURS_PER_DAY = 540